name: offside
description: Offside match betting
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^4.0.0
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  google_fonts: ^8.0.0
  json_annotation: ^4.9.0
  get_it: ^9.2.0
  shared_preferences: ^2.2.1
  chopper: ^8.5.0
  gap: ^3.0.1
  intl: ^0.20.2
  supercharged: ^2.1.1
  skeletonizer: ^2.1.1
  simple_animations: ^5.0.2
  animations: ^2.0.10
  bottom_sheet: ^4.0.0
  loading_animations: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  collection: ^1.18.0
  hl_image_picker: ^1.2.13
  cached_network_image: ^3.3.1
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.14.4
  d_chart: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.4.6
  freezed: ^3.2.3
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/images/logo_macos_1024.png"

flutter:
  assets:
    - assets/images/teams/germany.png
    - assets/images/teams/scotland.png
    - assets/images/teams/hungary.png
    - assets/images/teams/switzerland.png
    - assets/images/teams/spain.png
    - assets/images/teams/croatia.png
    - assets/images/teams/italy.png
    - assets/images/teams/albania.png
    - assets/images/teams/slovenia.png
    - assets/images/teams/denmark.png
    - assets/images/teams/serbia.png
    - assets/images/teams/england.png
    - assets/images/teams/netherlands.png
    - assets/images/teams/france.png
    - assets/images/teams/poland.png
    - assets/images/teams/austria.png
    - assets/images/teams/ukraine.png
    - assets/images/teams/slovakia.png
    - assets/images/teams/belgium.png
    - assets/images/teams/romania.png
    - assets/images/teams/portugal.png
    - assets/images/teams/czech.png
    - assets/images/teams/georgia.png
    - assets/images/teams/turkey.png

  uses-material-design: true
