name: offside
description: Offside match betting
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  riverpod: ^2.3.7
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.1.2
  go_router: ^10.1.0
  flutter_riverpod: ^2.3.7
  google_fonts: ^5.1.0
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  chopper: ^7.0.6
  gap: ^3.0.1
  intl: ^0.18.1
  supercharged: ^2.1.1
  skeletonizer: ^0.8.0
  simple_animations: ^5.0.2
  animations: ^2.0.10
  bottom_sheet: ^4.0.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  loading_animations: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.2.6
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/teams/england.png
    - assets/images/teams/poland.png
    - assets/images/teams/italy.png
    - assets/images/teams/germany.png
    - assets/images/profile.jpg
  uses-material-design: true