name: offside
description: Offside match betting
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  riverpod: ^2.3.7
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.1.2
  go_router: ^13.2.2
  flutter_riverpod: ^2.3.7
  google_fonts: ^6.2.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  chopper: ^7.0.6
  gap: ^3.0.1
  intl: ^0.19.0
  supercharged: ^2.1.1
  skeletonizer: ^1.1.1
  simple_animations: ^5.0.2
  animations: ^2.0.10
  bottom_sheet: ^4.0.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  loading_animations: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  collection: ^1.18.0
  firebase_auth: ^4.18.0
  firebase_storage: ^11.7.2
  hl_image_picker: ^1.2.13
  cached_network_image: ^3.3.1
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.13.1
  d_chart: ^2.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.2.6
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/images/logo_macos_1024.png"

flutter:
  assets:
    - assets/images/teams/germany.png
    - assets/images/teams/scotland.png
    - assets/images/teams/hungary.png
    - assets/images/teams/switzerland.png
    - assets/images/teams/spain.png
    - assets/images/teams/croatia.png
    - assets/images/teams/italy.png
    - assets/images/teams/albania.png
    - assets/images/teams/slovenia.png
    - assets/images/teams/denmark.png
    - assets/images/teams/serbia.png
    - assets/images/teams/england.png
    - assets/images/teams/netherlands.png
    - assets/images/teams/france.png
    - assets/images/teams/poland.png
    - assets/images/teams/austria.png
    - assets/images/teams/ukraine.png
    - assets/images/teams/slovakia.png
    - assets/images/teams/belgium.png
    - assets/images/teams/romania.png
    - assets/images/teams/portugal.png
    - assets/images/teams/czech.png
    - assets/images/teams/georgia.png
    - assets/images/teams/turkey.png

  uses-material-design: true