name: offside
description: Offside match betting
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  riverpod: ^3.1.0
  dart_mappable: ^4.3.0
  riverpod_annotation: ^4.0.0
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  google_fonts: ^8.0.0
  json_annotation: ^4.9.0
  get_it: ^9.2.0
  shared_preferences: ^2.2.1
  dio: ^5.4.0
  retrofit: ^4.4.2
  gap: ^3.0.1
  intl: ^0.20.2
  supercharged: ^2.1.1
  skeletonizer: ^2.1.1
  simple_animations: ^5.0.2
  animations: ^2.0.10
  bottom_sheet: ^4.0.0
  loading_animations: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  collection: ^1.18.0
  hl_image_picker: ^1.2.13
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.14.4
  d_chart: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.3.0
  retrofit_generator: ^10.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/images/logo_macos_1024.png"

flutter:
  assets:
    - assets/images/teams/alb.png
    - assets/images/teams/aut.png
    - assets/images/teams/bel.png
    - assets/images/teams/cro.png
    - assets/images/teams/cze.png
    - assets/images/teams/den.png
    - assets/images/teams/eng.png
    - assets/images/teams/esp.png
    - assets/images/teams/fra.png
    - assets/images/teams/geo.png
    - assets/images/teams/ger.png
    - assets/images/teams/hun.png
    - assets/images/teams/ita.png
    - assets/images/teams/ned.png
    - assets/images/teams/pol.png
    - assets/images/teams/por.png
    - assets/images/teams/rou.png
    - assets/images/teams/sco.png
    - assets/images/teams/ser.png
    - assets/images/teams/slo.png
    - assets/images/teams/sui.png
    - assets/images/teams/svk.png
    - assets/images/teams/tur.png
    - assets/images/teams/ukr.png

  uses-material-design: true
